export const LOGIN = 'LOGIN'
export const LOGIN_STATUS = 'LOGIN_STATUS'
export const ENTERPRISE_GET_LIST_CV = 'ENTERPRISE_GET_LIST_CV'
export const E_DETAIL_CV = 'E_DETAIL_CV'
export const M_LIST_CV = 'M_LIST_CV'
export const M_DETAIL_CV = 'M_DETAIL_CV'
export const LIST_SESSION = 'LIST_SESSION'
export const SESSION_DETAIL = 'SESSION_DETAIL'
